name: CI/CD Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: "Tests Laravel"
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql, xml

      - name: Installer les dépendances
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Copier .env
        run: cp .env.example .env

      - name: Générer la clé
        run: php artisan key:generate

      - name: Migrations SQLite en mémoire
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: php artisan migrate --force

      - name: Lancer les tests
        run: php artisan test
